[package]
org = "ballerinax"
name = "health.fhir.r4utils.jsonmerge"
version = "1.0.0"
distribution = "2201.12.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils", "JSONMerge"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"