[package]
org = "ballerinax"
name = "health.fhir.r4utils"
version = "1.0.0"
distribution = "2201.4.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils"]
export = ["health.fhir.r4utils"]
repository="https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
