openapi: 3.0.3
info:
  title: Enrich Analytics Payload API
  version: 1.0.0
  description: 'API to enrich analytics payload with additional information before publishing.'
paths:
  /enrich-analytics-payload:
    post:
      summary: Accepts and returns a JSON object with arbitrary string fields.
      requestBody:
        description: JSON input with arbitrary keys and string values
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        '200':
          description: JSON output with arbitrary keys and string values
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string