name: daily-build-davincidtr210

on:
  schedule:
    - cron: "15 21 * * *"  # 02:45 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/daily-build-executor.yml
    secrets: inherit
    with:
      working_dir: davincidtr210
