name: daily-build-fhirpath

on:
  schedule:
    - cron: '20 20 * * *'    # 01:50 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
     uses: ./.github/workflows/daily-build-executor.yml
     secrets: inherit
     with:
      working_dir: utils/fhirpath
      